name: Update Table of Contents

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Doctoc
        run: npm install -g doctoc

      - name: Generate Table of Contents
        run: doctoc README.md

      - name: Commit changes and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update Table of Contents" || echo "No changes to commit"
          git push
